@startuml
title Сражение с боссом: диаграмма деятельности

|Бегун|
start
:Выбрать босса;
:Начать бой;

|Приложение|
:Запросить данные босса и персонажа;

|Сервер|
:Получить параметры из базы данных;
:Вернуть HP босса и характеристики;

|Приложение|
:Запустить отслеживание GPS;

repeat
  :Получить координаты от GPS-сервиса;
  :Рассчитать дистанцию и темп\n(скользящее окно 30-60 с);

  |Сервер|
  if (Темп допустим?) then (да)
    :Рассчитать урон =\nдистанция × базовый урон × множитель темпа;
    :Уменьшить HP босса;
  else (нет)
    :Не засчитывать отрезок;
  endif

  |Приложение|
  :Обновить полоску HP босса;

  |Бегун|
repeat while (HP босса > 0 и бегун не завершил пробежку?) is (да) not (нет)

|Приложение|
:Остановить отслеживание GPS;

|Сервер|
if (HP босса = 0?) then (победа)
  :Начислить опыт;
  :Выдать награду;
else (досрочное завершение)
  :Начислить опыт только за дистанцию;
endif

if (Опыта достаточно для нового уровня?) then (да)
  :Повысить уровень;
  :Начислить очки прокачки;
else (нет)
endif

:Сохранить результат в базе данных;

|Приложение|
:Показать итоговый экран;

|Бегун|
stop
@enduml